--  Generate SQL
--  Version:                   	V7R4M0 190621
--  Generated on:              	03/18/24 12:38:42
--  Relational Database:       	RDB_EIWEBDEV
--  Standards Option:          	Db2 for i
SET PATH *LIBL ;

CREATE PROCEDURE PJS_ENV/ADDATRIUMMENUOPTIONS ( )
	LANGUAGE SQL
	SPECIFIC PJS_ENV/ADDATRIUMMENUOPTIONS
	NOT DETERMINISTIC
	MODIFIES SQL DATA
	CALLED ON NULL INPUT
	SET OPTION  ALWBLK = *ALLREAD ,
	ALWCPYDTA = *OPTIMIZE ,
	COMMIT = *NONE ,
	DECRESULT = (31, 31, 00) ,
	DYNDFTCOL = *NO ,
	DYNUSRPRF = *USER ,
	SRTSEQ = *HEX
	BEGIN
-- Declare variables
DECLARE V_AAUSER INT ;
DECLARE V_ANITEM INT ;
DECLARE V_ANSEQ INT ;
DECLARE V_ANPARENT INT ;

DECLARE V_PGM CHAR ( 10 ) ;
DECLARE V_ANKEYWORDS CHAR ( 128 ) ;
DECLARE V_ANVVALUE CHAR ( 128 ) ;
DECLARE V_AUUSER INT ;
DECLARE V_AUPROF CHAR ( 10 ) ;

-- Declare cursor for the file
FOR V1 AS CSR1 CURSOR FOR
SELECT DISTINCT A . PGM AS PGM , B . ANTEXT AS ANTEXT , B . ANKEYWORDS AS ANKEYWORDS , X . ANVVALUE AS ANVVALUE , C . AUUSER AS AUUSER , C . AUPROF AS AUPROF
FROM QGPL / EI001P1 A
LEFT OUTER JOIN PUITRFMJCW / ATNAVP B
ON A . PGM = UPPER ( B . ANKEYWORDS )
LEFT OUTER JOIN PUITRFMJCW / ATNVARSP X
ON X . ANVITEM = B . ANITEM
LEFT OUTER JOIN PUITRFMJCW / ATUSERSP C
ON A . USERN = C . AUPROF
LEFT OUTER JOIN PUITRFMJCW / ATAUTHP D
ON C . AUUSER = D . AAID
LEFT OUTER JOIN PUITRFMJCW / ATNAVP E
ON B . ANPARENT = E . ANITEM
LEFT OUTER JOIN PUITRFMJCW / ATAUTHP F
ON E . ANITEM = F . AAITEM
AND D . AAID = F . AAID
WHERE F . AAITEM IS NULL
AND E . ANITEM <> 1
AND C . AUPROF IS NOT NULL
ORDER BY B . ANKEYWORDS

DO
-- Fetch a record
SET V_PGM = PGM ;
SET V_ANITEM = ANITEM ;
SET V_ANTEXT = ANTEXT ;
SET V_ANKEYWORDS = ANKEYWORDS ;
SET V_ANVALUE = ANVALUE ;
SET V_AUUSER = AUUSER ;
SET V_AUPROF = AUPROF ;

-- Get Parent Based on first 2 characters of program name
SELECT ANITEM INTO V_ANPARENT FROM PUITRFMJCW / ATNAVP WHERE UPPER ( SUBSTRING ( ANKEYWORDS FROM 1 FOR 2 ) ) = UPPER ( SUBSTRING ( V_PGM FROM 1 FOR 2 ) ) AND ANTYPE = 0 AND ANPARENT = 0 ;

-- Get Max Sequence Number
SELECT MAX ( ANSEQ ) + 1 INTO V_ANSEQ FROM PUITRFMJCW / ATNAVP WHERE ANPARENT = V_ANPARENT ;

-- Get Next Item Number
SELECT MAX ( ANITEM ) + 1 INTO V_ANITEM FROM PUITRFMJCW / ATNAVP ;

--Insert Navigation Item
INSERT INTO PUITRFMJCW / ATNAVP ( ANSECT , ANITEM , ANSEQ , ANPARENT , ANTYPE , ANACTNTYPE , ANACTN , ANTEXT , ANICON , ANWINDOW , ANGURL , ANONCE , ANPARM , ANKEYWORDS ) VALUES ( 'N' , V_ANITEM , V_ANSEQ , V_ANPARENT , 1 , 1 , 1 , V_ANTEXT , '' , '' , '' , '' , '' , V_ANKEYWORDS ) ;
INSERT INTO PUITRFMJCW / ATNVARSP ( ANVITEM , ANVNAME , ANVVALUE ) VALUES ( V_ANITEM , 'cmdpgm' , V_ANVVALUE ) ;

-- Insert Permissions
INSERT INTO PUITRFMJCW / ATAUTHP ( AAITEM , AAID , AAALLOW ) VALUES ( V_ANITEM , V_AUUSER , '1' ) ;

END FOR ;

-- Update Next Number for Navigation Items
UPDATE PUITRFMJCW / ATUIDSP SET AUINEXT = ( SELECT COUNT ( * ) + 1 FROM PUITRFMJCW / ATNAVP ) WHERE AUIFIELD = 'ANITEM' ;

END  ;

GRANT ALTER , EXECUTE
ON SPECIFIC PROCEDURE PJS_ENV/ADDATRIUMMENUOPTIONS
TO PROFOUND WITH GRANT OPTION ;

GRANT EXECUTE
ON SPECIFIC PROCEDURE PJS_ENV/ADDATRIUMMENUOPTIONS
TO PUBLIC ;

